camera:
  width: 1280
  height: 720
  fps: 30

display:
  enabled: true
  window_name: raspi-hud

logging:
  level: INFO

mavlink:
  connection: udp:127.0.0.1:14550
  baudrate: 57600
  source: "pymavlink"